user:
  results:
    result: null
    reason: null
    IF: null
    request_time: null
    response_time: null
  scripts:
    Contents:
    - yn_adult|wat_lvl_cd^rslu_typ_cd|yn_adult = 'N'; if (wat_lvl_cd >= '15') yn_adult = 'Y';
    - yn_adult2|wat_lvl_cd^rslu_typ_cd|yn_adult2 = 'N'; if (wat_lvl_cd >= '19') yn_adult2 = 'Y';
  api:
    contents_synopsis:
      redis: contents
      field: con_id
      essential: con_id
      params: con_id,new_series,id_package
      response_name: contents
  defaults:
    menu_stb_svc_id: UI50_BSUHD2
  cw:
    baseurl: http://skb-devph2-cwall.contentwise.tv
    fullsection:
      uri: /parallelApi/v6/CW/ux/{cw_call_id}/page
      param: sessionId,trackId,{param},itemType
      nxpgparam: session_id,track_id,{param},itemType
    multisection:
      uri: /parallelApi/v6/CW/ux/{cw_call_id}/page/sections
      param: sectionIds,sessionId,trackId,{param},itemType
      nxpgparam: section_id,session_id,track_id,{param},itemType
    onlysection:
      uri: /v6/CW/ux/{cw_call_id}/page
      param: retrieveSections,{param},itemType
      nxpgparam: retrieveSections,{param},itemType
    getonepage:
      uri: /v6/CW/ux/{cw_call_id}/page
      param: sessionId,trackId,{param},itemType
      nxpgparam: session_id,track_id,{param},itemType
    getonesection:
      uri: /v6/CW/ux/{cw_call_id}/page/section
      param: sectionId,sessionId,trackId,{param},itemType
      nxpgparam: section_id,session_id,track_id,{param},itemType
    userpage:
      uri: /v6/CW/users/{stb_id}
    user: admin
    password: admin
    block:
      cmpgn_apl_to_dt: null
      cmpgn_nm: null
      is_leaf: Y
      cmpgn_fr_dt: null
      dist_to_dt: null
      menu_nm_exps_yn: null
      menu_id: null
      gnb_typ_cd: null
      scn_mthd_cd: null
      dist_fr_dt: null
      cmpgn_to_dt: null
      menu_exps_prop_cd: null
      cmpgn_itlk_typ_cd: null
      blk_typ_cd: '30'
      exps_mthd_cd: '10'
      svc_prop_cd: null
      chrtr_menu_cat_cd: null
      cmpgn_apl_fr_dt: null
      call_typ_cd: null
      cmpgn_id: null
      call_url: null
      menu_expl: null
      menu_nm: null
      pst_exps_typ_cd: null
      lim_lvl_yn: N
      menus: null
    calltypcd: '22'
spring:
  http:
    encoding:
      charset: UTF-8
  jackson:
    default-property-inclusion: NON_NULL
  redis:
    host: 10.10.123.8:6379,10.10.123.9:6379,10.10.123.10:6379,10.10.123.11:6379,10.10.123.12:6379,10.10.123.13:6379
    port: 6379
    password: xaetahgeki4lieB7Ouz9ieju4bahyeiC
second:
  redis:
    host: 10.10.123.8:6379,10.10.123.9:6379,10.10.123.10:6379,10.10.123.11:6379,10.10.123.12:6379,10.10.123.13:6379
    port: 6379
    password: xaetahgeki4lieB7Ouz9ieju4bahyeiC
services:
  redis:
    connection:
      timeout: 400
    redirection:
      count: 1
management:
  security:
    enabled: false
zuul:
  routes:
    ge:
      path: /ge/**
      url: http://10.10.123.39:8080