management:
  security:
    enabled: false
spring:
  http:
    encoding:
      charset: UTF-8
  redis:
    host: 10.10.223.35:6379,10.10.223.36:6379,10.10.223.37:6379,10.10.223.38:6379,10.10.223.39:6379,10.10.223.40:6379
    port: 6379
    password: gogwi0m3wMmsUXac22hCn8kstwLaiCCj
    setMaxTotal: 600 
    setMaxIdle: 60
    setMinIdle: 30
second:
  redis:
    host: 10.10.223.35:6379,10.10.223.36:6379,10.10.223.37:6379,10.10.223.38:6379,10.10.223.39:6379,10.10.223.40:6379
    port: 6379
    password: gogwi0m3wMmsUXac22hCn8kstwLaiCCj
    switching-milisecond: 500
zuul:
  routes:
    ge:
      path: /ge/**
      url: http://10.10.223.30:8080
task:
  fixedThreadPool:
    maxCount: 200
  threadPoolTaskExecutor:
    corePoolSize: 200
    maxPoolSize: 300
    queueCapacity: 500
services:
  redis:
    connection:
      timeout: 1000
    redirection:
      count: 1
user:
  cwswitch: true
  expiryDate: true
  cimodeCheck: 20,30,34,35,41,42
  useLogForResponseData: false
  checkVersionEqual: true
  checkdate:
    ppmorgnzfrdt: 7
    ppmorgnztodt: 7
    prdprctodt: 14
    nextprdprcfrdt: 3
  results:
    result: null
    reason: null
    IF: null
    request_time: null
    response_time: null
  defaults:
    menu_stb_svc_id: BTVUH2V500
  cw:
    baseurl: https://skb-prod-ph2-api.contentwise.tv
    fullsection: 
      uri: /parallelApi/v6/CW/ux/{cw_call_id}/page
      param: sessionId,trackId,{param},itemType
      nxpgparam: session_id,track_id,{param},itemType
    multisection:
      uri: /parallelApi/v6/CW/ux/{cw_call_id}/page/sections
      param: sectionIds,sessionId,trackId,{param},itemType
      nxpgparam: section_id,session_id,track_id,{param},itemType
    onlysection:
      uri: /v6/CW/ux/{cw_call_id}/page
      param: retrieveSections,{param},itemType
      nxpgparam: retrieveSections,{param},itemType
    getonepage:
      uri: /v6/CW/ux/{cw_call_id}/page
      param: sessionId,trackId,{param},itemType
      nxpgparam: session_id,track_id,{param},itemType
    getonesection:
      uri: /v6/CW/ux/{cw_call_id}/page/section
      param: sectionId,sessionId,trackId,{param},itemType
      nxpgparam: section_id,session_id,track_id,{param},itemType
    userpage:
      uri: /v6/CW/users/{stb_id}
    user: admin
    password: admin
    block:
      cmpgn_apl_to_dt: 
      cmpgn_nm: 
      is_leaf: Y
      cmpgn_fr_dt: 
      dist_to_dt: null
      menu_nm_exps_yn: 
      menu_id: 
      gnb_typ_cd: null
      scn_mthd_cd: 
      dist_fr_dt: null
      cmpgn_to_dt: 
      menu_exps_prop_cd: 
      cmpgn_itlk_typ_cd: 
      blk_typ_cd: "30"
      exps_mthd_cd: "10"
      svc_prop_cd: 
      chrtr_menu_cat_cd: 
      cmpgn_apl_fr_dt: 
      call_typ_cd: 
      cmpgn_id: 
      call_url: 
      menu_expl: 
      menu_nm: 
      pst_exps_typ_cd: 
      lim_lvl_yn: N
      menus: null
    grid:
      sale_prc: 0
      poster_filename_v:
      user_badge_img_path:
      svc_fr_dt:
      epsd_id:
      title:
      synon_typ_cd:
      user_badge_wdt_img_path:
      poster_filename_h:
      icon_exps_fr_dt:
      wat_lvl_cd:
      adlt_lvl_cd:
      bas_badge_img_path:
      i_img_cd:
      brcast_tseq_nm:
      first_epsd_id:
      meta_typ_cd:
      sris_id:
      icon_exps_to_dt:
      sris_cmpt_yn:
      sort_seq: 0
      svc_to_dt:
      epsd_dist_fir_svc_dt:
      sris_dist_fir_svc_dt:
      track_id:
      badge_typ_nm:
      rslu_typ_cd:
      kids_yn:
      cacbro_yn:
    scnmthdcd: "502"
    socktimeout: 3000
    conntimeout: 3000
    connreqtimeout: 3000
  logging:
    name: ${vcap.application.name}
    instance_index: ${vcap.application.instance_index}