user:
  results:
    result: null
    reason: null
    IF: null
    request_time: null
    response_time: null
  scripts:
    Contents:
    - yn_adult|wat_lvl_cd^rslu_typ_cd|yn_adult = 'N'; if (wat_lvl_cd >= '15') yn_adult = 'Y';
    - yn_adult2|wat_lvl_cd^rslu_typ_cd|yn_adult2 = 'N'; if (wat_lvl_cd >= '19') yn_adult2 = 'Y';
  api:
    contents_synopsis:
      redis: contents
      field: con_id
      essential: con_id
      params: con_id,new_series,id_package
      response_name: contents
  defaults:
    menu_stb_svc_id: UI50_BSUHD2
  cw:
    baseurl: http://skb-devph2-cwall.contentwise.tv
    fullsection: 
      uri: /parallelApi/v6/CW/ux/{cw_call_id}/page
      param: user,sessionId,trackId
      nxpgparam: stb_id,session_id,track_id
    multisection:
      uri: /parallelApi/v6/CW/ux/{cw_call_id}/page/sections
      param: user,sectionIds,sessionId,trackId
      nxpgparam: stb_id,section_id,session_id,track_id
    onlysection:
      uri: /v6/CW/ux/{cw_call_id}/page
      param: user,retrieveSections
      nxpgparam: stb_id,retrieveSections
    getonepage:
      uri: /v6/CW/ux/{cw_call_id}/page
      param: user,sessionId,trackId
      nxpgparam: stb_id,session_id,track_id
    getonesection:
      uri: /v6/CW/ux/{cw_call_id}/page/section
      param: user,sectionId,sessionId,trackId
      nxpgparam: stb_id,section_id,session_id,track_id
    user: admin
    password: admin
spring:
  http:
    encoding:
      charset: UTF-8
  jackson:
    default-property-inclusion: NON_NULL
#    generator:
#      write-numbers-as-strings: true
  redis:
    host: localhost
    port: 6379
    password: null
management:
  security:
    enabled: false
zuul:
  routes:
    ge:
      path: /ge/**
      url: http://localhost:8090