user:
  results:
    result: null
    reason: null
    IF: null
    request_time: null
    response_time: null
  scripts:
    Contents:
    - yn_adult|wat_lvl_cd^rslu_typ_cd|yn_adult = 'N'; if (wat_lvl_cd >= '15') yn_adult = 'Y';
    - yn_adult2|wat_lvl_cd^rslu_typ_cd|yn_adult2 = 'N'; if (wat_lvl_cd >= '19') yn_adult2 = 'Y';
  api:
    contents_synopsis:
      redis: contents
      field: con_id
      essential: con_id
      params: con_id,new_series,id_package
      response_name: contents
  defaults:
    menu_stb_svc_id: UI50_BSUHD2
  cw:
    baseurl: http://skb-devph2-cwall.contentwise.tv
    fullsection: 
      uri: /parallelApi/v6/CW/ux/{cw_call_id}/page
      param: sessionId,trackId,{param},itemType
      nxpgparam: session_id,track_id,{param},itemType
    multisection:
      uri: /parallelApi/v6/CW/ux/{cw_call_id}/page/sections
      param: sectionIds,sessionId,trackId,{param},itemType
      nxpgparam: section_id,session_id,track_id,{param},itemType
    onlysection:
      uri: /v6/CW/ux/{cw_call_id}/page
      param: retrieveSections,{param},itemType
      nxpgparam: retrieveSections,{param},itemType
    getonepage:
      uri: /v6/CW/ux/{cw_call_id}/page
      param: sessionId,trackId,{param},itemType
      nxpgparam: session_id,track_id,{param},itemType
    getonesection:
      uri: /v6/CW/ux/{cw_call_id}/page/section
      param: sectionId,sessionId,trackId,{param},itemType
      nxpgparam: section_id,session_id,track_id,{param},itemType
    userpage:
      uri: /v6/CW/users/{stb_id}
    user: admin
    password: admin
    block:
      cmpgn_apl_to_dt: 
      cmpgn_nm: 
      is_leaf: Y
      cmpgn_fr_dt: 
      dist_to_dt: null
      menu_nm_exps_yn: 
      menu_id: 
      gnb_typ_cd: null
      scn_mthd_cd: 
      dist_fr_dt: null
      cmpgn_to_dt: 
      menu_exps_prop_cd: 
      cmpgn_itlk_typ_cd: 
      blk_typ_cd: "30"
      exps_mthd_cd: "10"
      svc_prop_cd: 
      chrtr_menu_cat_cd: 
      cmpgn_apl_fr_dt: 
      call_typ_cd: 
      cmpgn_id: 
      call_url: 
      menu_expl: 
      menu_nm: 
      pst_exps_typ_cd: 
      lim_lvl_yn: N
      menus: null
    scnmthdcd: "502"
spring:
  http:
    encoding:
      charset: UTF-8
  jackson:
    default-property-inclusion: NON_NULL
  redis:
    host: 10.10.113.8
    port: 6379
    password: eera9eizohxiengaF9iemai3zuc4oogh
second:
  redis:
    host: 10.10.113.8
    port: 6379
    password: eera9eizohxiengaF9iemai3zuc4oogh
management:
  security:
    enabled: false
zuul:
  routes:
    ge:
      path: /ge/**
      url: http://10.10.113.12:8080