spring:
  http:
    encoding:
      charset: UTF-8
  data:
    mongodb:
      host: localhost
      port: 27017
      database: xpg_mp
btv:
  point: 6.0
server:
  image:
    url: http://image.hanafostv.com:8080/meta/
local:
  redis:
    host: localhost
    port: 6379
    password: null
logging:
  pattern:
    console: '%d|%p|%m%n'
    file: '%d|%p|%m%n'
  level:
    com:
      skb:
        xpg: DEBUG