user:
  cwswitch: true
  logswitch: false
  results:
    result: null
    reason: null
    IF: null
    request_time: null
    response_time: null
  defaults:
    menu_stb_svc_id: UI50_BSUHD2
  cw:
    baseurl: http://skb-devph2-cwall.contentwise.tv
    fullsection: 
      uri: /parallelApi/v6/CW/ux/{cw_call_id}/page
      param: sessionId,trackId,{param},itemType
      nxpgparam: session_id,track_id,{param},itemType
    multisection:
      uri: /parallelApi/v6/CW/ux/{cw_call_id}/page/sections
      param: sectionIds,sessionId,trackId,{param},itemType
      nxpgparam: section_id,session_id,track_id,{param},itemType
    onlysection:
      uri: /v6/CW/ux/{cw_call_id}/page
      param: retrieveSections,{param},itemType
      nxpgparam: retrieveSections,{param},itemType
    getonepage:
      uri: /v6/CW/ux/{cw_call_id}/page
      param: sessionId,trackId,{param},itemType
      nxpgparam: session_id,track_id,{param},itemType
    getonesection:
      uri: /v6/CW/ux/{cw_call_id}/page/section
      param: sectionId,sessionId,trackId,{param},itemType
      nxpgparam: section_id,session_id,track_id,{param},itemType
    userpage:
      uri: /v6/CW/users/{stb_id}
    user: admin
    password: admin
    block:
      cmpgn_apl_to_dt: 
      cmpgn_nm: 
      is_leaf: Y
      cmpgn_fr_dt: 
      dist_to_dt: 
      menu_nm_exps_yn: 
      menu_id: 
      gnb_typ_cd: 
      scn_mthd_cd: 
      dist_fr_dt: 
      cmpgn_to_dt: 
      menu_exps_prop_cd: 
      cmpgn_itlk_typ_cd: 
      blk_typ_cd: "30"
      exps_mthd_cd: "10"
      svc_prop_cd: 
      chrtr_menu_cat_cd: 
      cmpgn_apl_fr_dt: 
      call_typ_cd: 
      cmpgn_id: 
      call_url: 
      menu_expl: 
      menu_nm: 
      pst_exps_typ_cd: 
      lim_lvl_yn: N
      menus: null
    grid:
      sale_prc: 0
      poster_filename_v:
      user_badge_img_path:
      svc_fr_dt:
      epsd_id:
      title:
      synon_typ_cd:
      user_badge_wdt_img_path:
      poster_filename_h:
      icon_exps_fr_dt:
      wat_lvl_cd:
      adlt_lvl_cd:
      bas_badge_img_path:
      i_img_cd:
      brcast_tseq_nm:
      meta_typ_cd:
      sris_id:
      icon_exps_to_dt:
      sort_seq: 0
      svc_to_dt:
      epsd_dist_fir_svc_dt:
      sris_dist_fir_svc_dt:
      track_id:
      badge_typ_nm:
      rslu_typ_cd:
      kids_yn:
      cacbro_yn:
    scnmthdcd: "502"
    socktimeout: 2000
    conntimeout: 300
    connreqtimeout: 300
  logging:
    name: xpg-nxpg-svc
    instance_index: 0
spring:
  http:
    encoding:
      charset: UTF-8
  jackson:
    default-property-inclusion: NON_NULL
  redis:
    host: localhost
    port: 6379
    password: null
second:
  redis:
    host: localhost
    port: 6379
    password: null
    switching-milisecond: 500
management:
  security:
    enabled: false
endpoints:
  restart:
    enabled: true
zuul:
  routes:
    ge:
      path: /ge/**
      url: http://localhost:8090